### ISSUE TITLE
Configuration warning unrecognized property 'ssmToEnvironment'

### ISSUE THREAD

**Issue by ats-org** [gozup/serverless-ssm-fetch#12]
Greetings,

I don't think this is a big problem cause it looks like the environment variables are getting propagated. however, there is a warning when running with sls offline

```
Serverless: Configuration warning:
Serverless:   at 'functions.handler': unrecognized property 'ssmToEnvironment'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

```
functions:
  create:
      handler: src/handler
      events:
        - http:
            path: create
            method: post
            cors: true
      ssmToEnvironment:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - DB_PORT
        - CORS_DOMAIN
```
