### ISSUE TITLE
Not working with dotenv

### ISSUE THREAD

**Issue by Fyb3roptik** [gozup/serverless-ssm-fetch#19]
I am using Golang and this is not working for me.

As an example I set `DB_HOST` and when i do `os.Getenv("DB_HOST")` It comes back blank. Am I missing something??

I added a blank DB_HOST to the .env file in hopes it would work, but when I run this locally it does not work. Am I only able to get this to work if I deploy?? If so then that does not help me with local dev

**Comment by Fyb3roptik** [comment]
```
serverlessSsmFetch:
    DB_NAME: /db-database~true
    DB_USER: /db-user~true
    DB_PASSWORD: /db-password~true
    DB_HOST: /db-host~true
    DB_PORT: /db-port~true
```

**Comment by DobleV55** [comment]
+1 It doesn't work for me neither, I'm using Golang

**Comment by gozup** [comment]
Hello,

I want to clarify the purpose of the `serverless-ssm-fetch` plugin, which seems to have been misunderstood. This plugin's role is to fetch parameters stored in AWS SSM dynamically during deployment and set them as environment variables on Lambda. It is meant to be used as an `infrastructure` plugin, rather than a `code` plugin.

While developing locally, you should use environment variables defined in your local .env file at the code level. However, when you deploy your code, the plugin will automatically set environment variables stored at the Lambda container level.

I hope this clears up any confusion. Cheers!

**Comment by DobleV55** [comment]
In mi case, im not being able to set the env variables on the deploy. 
This is my serverless/yml:
```
...
  go-lambda-create-user:
    handler: lambdas/bin/go-lambda-create-user
    ssmToEnvironment:
      - EMAIL_SENDER_ADDRESS
      - EMAIL_SENDER_PASSWORD
    events:
      - httpApi:
          path: /create-user
          method: post
      - cloudwatchLog: '/aws/lambda/go-lambda-create-user'
...
plugins:
  - serverless-ssm-fetch

custom:
  serverlessSsmFetch:
    EMAIL_SENDER_ADDRESS: /aws/ssm/email_sender_address~true
    EMAIL_SENDER_PASSWORD: /aws/ssm/email_sender_password~true
```


When I deploy I dont get any error but theres no env variable in my lambda.

**Comment by gozup** [comment]
Did you properly set the parameters on AWS Console, here: https://us-east-1.console.aws.amazon.com/systems-manager/parameters/?region=us-east-1&tab=Table

If yes, are you targeting the correct region ? With correct credentials ?

**Comment by DobleV55** [comment]
Here are my parameters, they are in sa-east-1
<img width="1597" alt="Screenshot 2023-03-09 at 13 57 53" src="https://user-images.githubusercontent.com/24664579/224030130-3a901d44-4923-4b33-bdb7-9c0a99d8e95e.png">

**Comment by gozup** [comment]
Ok, that's where the mistake is.
In your `serverless.yml` you declared the following path: `/aws/ssm/email_sender_password` 
But in SSM you created `email_sender_password`. "El nombre" should be `/aws/ssm/email_sender_password`.
Tell me if if solved your problem.

**Comment by DobleV55** [comment]
When I try to create the SSM with the name `/aws/ssm/email_sender_address` or `aws/ssm/email_sender_address` in the AWS Console I get the following error:
`No access to reserved parameter name: aws/ssm/email_sender_address.`

**Comment by gozup** [comment]
Maybe 'aws' is a reserved word. You can actually set the path you want. Or just use `/email_sender_password ` in the console, but in this case you should use `EMAIL_SENDER_ADDRESS: /email_sender_address~true` in the `serverless.yml`

**Comment by DobleV55** [comment]
Im gonna create it like that, so you can check is everything okay
<img width="826" alt="Screenshot 2023-03-09 at 14 32 57" src="https://user-images.githubusercontent.com/24664579/224038481-13d16b3a-4643-4a27-b99b-02d4306a6cea.png">

**Comment by DobleV55** [comment]
This is my serverless.yml:

```
functions:
  go-lambda-create-user:
    handler: lambdas/bin/go-lambda-create-user
    ssmToEnvironment:
      - EMAIL_SENDER_ADDRESS
      - EMAIL_SENDER_PASSWORD
    events:
      - httpApi:
          path: /create-user
          method: post
      - cloudwatchLog: '/aws/lambda/go-lambda-create-user'
...
plugins:
  - serverless-ssm-fetch
  
custom:
  serverlessSsmFetch:
    EMAIL_SENDER_ADDRESS: /email_sender_address~true
    EMAIL_SENDER_PASSWORD: /email_sender_password~true
 
```
